# Generated by Django 5.1.1 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('longName', models.CharField(blank=True, max_length=255, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
                ('enterpriseValue', models.BigIntegerField(blank=True, null=True)),
                ('trailingPE', models.FloatField(blank=True, null=True)),
                ('forwardPE', models.FloatField(blank=True, null=True)),
                ('pegRatio', models.FloatField(blank=True, null=True)),
                ('priceToSalesTrailing12Months', models.FloatField(blank=True, null=True)),
                ('priceToBook', models.FloatField(blank=True, null=True)),
                ('enterpriseToRevenue', models.FloatField(blank=True, null=True)),
                ('enterpriseToEbitda', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekHigh', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekLow', models.FloatField(blank=True, null=True)),
                ('fiftyDayAverage', models.FloatField(blank=True, null=True)),
                ('twoHundredDayAverage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
